### ISSUE TITLE
Conda

### ISSUE THREAD

**Issue by ardeaf** [chalmerlowe/bokeh_tutorial#1]
Just got home from the meetup

As someone who only used pip before and never conda: was there a reason specific to bokeh that we used conda over pip? Perhaps that could have been briefly explained

**Comment by chalmerlowe** [comment]
@ardeaf thanks for leaving this comment. I appreciate it.
good point.

I will add some discussion relative to this issue. For now:

Jake has a great writeup on all things conda:

https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/

> Because conda arose from within the Python (more specifically PyData) community, many mistakenly assume that it is fundamentally a Python package manager. This is not the case: conda is designed to manage packages and dependencies within any software stack. In this sense, it's less like pip, and more like a cross-platform version of apt or yum.
> 
> If you use conda, you are already probably taking advantage of many non-Python packages; the following command will list the ones in your environment:
> 
> `$ conda search --canonical  | grep -v 'py\d\d'`
> On my system, there are 350 results: these are packages within my Conda/Python environment that are fundamentally unmanageable by Python-only tools like pip & virtualenv.
