### ISSUE TITLE
create navigation for all pages...

### ISSUE THREAD

**Issue by chalmerlowe** [chalmerlowe/bokeh_tutorial#2]
on the **refactor** branch

Using markdown tables, create navigation for each page.

```
|Previous|Table of Contents|Next|
|:------|:-----:|------:|
|[Name](url)|[Name](url)|[Name](url)|
```

the main README.md should have only one column: `Next` that links to lesson one.
the first page should have two columns: `Table of contents` and `Next`
the last file should have no `Next` column

**Comment by jpbatz** [comment]
"Table of Contents" looked funny as header and link, so did TOC in either place.  Used "Up", instead, but lmk - I can certainly change it as originally specified.
